---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:dhruvdarji1/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: dhruvdarji1/podinfo
      tag: dev-jhbsbink
    replicaCount: 1
    ingress:
      enabled: true
      spec:
      rules:
      - host: sampleappdev.dev-cluster-3.rancher.gks.gdc-pcs.com
        http:
          paths:
          - backend:
              serviceName: podinfo-dev
              servicePort: 9898
            path: /

    hpa:
      enabled: false
