---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: podinfo-prod
  chart:
    git: git@github.com:dhruvdarji1/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: dhruvdarji1/podinfo
      tag: 0.4.11
    replicaCount: 3
    ingress:
      enabled: true
      spec:
      rules:
      - host: sampleapp.dev-cluster-3.rancher.gks.gdc-pcs.com
        http:
          paths:
          - backend:
              serviceName: podinfo-prod
              servicePort: 9898
            path: /
