---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: podinfo-rc
  chart:
    git: git@github.com:dhruvdarji1/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: dhruvdarji1/podinfo
      tag: stg-q6kamtcv
    replicaCount: 2
    ingress:
      enabled: true
      spec:
      rules:
      - host: sampleappprod.dev-cluster-3.rancher.gks.gdc-pcs.com
        http:
          paths:
          - backend:
              serviceName: podinfo-prod
              servicePort: 9898
            path: /
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
